### ISSUE TITLE
SDK crashes on Android 9 API_28

### ISSUE THREAD

**Issue by jrsarath** [Suraj-Tiwari/react-native-payumoney#24]
Trying the app on a Android One Real device and on a Emulator, Android 9 API_28
Here is the log from android studio 

=========================================================

2019-08-20 06:03:00.791 9314-9314/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gamesetter, PID: 9314
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gamesetter/com.payumoney.sdkui.ui.activities.PayUmoneyActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.payumoney.core.PayUmoneySDK.addPayment(com.payumoney.core.listener.OnPaymentOptionReceivedListener, java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.payumoney.core.PayUmoneySDK.addPayment(com.payumoney.core.listener.OnPaymentOptionReceivedListener, java.lang.String)' on a null object reference
        at com.payumoney.sdkui.ui.activities.PayUmoneyActivity.onCreate(PayUmoneyActivity.java:105)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:198) 
        at android.app.ActivityThread.main(ActivityThread.java:6729) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by jrsarath** [comment]
`<uses-library android:name="org.apache.http.legacy" android:required="false"/>`
on manifest fixed the issue
