### ISSUE TITLE
Issue in release build

### ISSUE THREAD

**Issue by musthafa8230** [Suraj-Tiwari/react-native-payumoney#39]
In debug build everything working fine but on release build it showing merchant I'd missing please help

**Comment by Suraj-Tiwari** [comment]
Same credentials? or credentials were changed?

**Comment by musthafa8230** [comment]
Credentials are same didn't changed anything

**Comment by musthafa8230** [comment]
After releasing in play store it's opening like this but in debug mode with
same credentials it's redirected to payumoney

**Comment by Suraj-Tiwari** [comment]
Okay I'll check it tomorrow.

**Comment by musthafa8230** [comment]
Ok thanks should we give isdebug true or false for release build

**Comment by Suraj-Tiwari** [comment]
that's for credentials, so it should be irrelevant.

**Comment by musthafa8230** [comment]
Oh ok👍 I had given false

**Comment by musthafa8230** [comment]
2020-08-01 00:42:41.572 5822-5946/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.xxxxx.app, PID: 5822
    java.lang.RuntimeException:  Merchant id missing
        at com.payumoney.core.d$a.<init>(SourceFile:124)
        at com.payumoney.core.d$a.<init>(SourceFile:108)
        at com.payumoney.core.d$a$a.aMP(SourceFile:427)
        at com.surajtiwari.reactnativepayumoney.RNPayumoneyModule.pay(SourceFile:59)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:29)
        at android.os.Looper.loop(Looper.java:201)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:232)
        at java.lang.Thread.run(Thread.java:764)

**Comment by Suraj-Tiwari** [comment]
check for minification in you android/app/build.gradle 
This could be causing issue `def enableProguardInReleaseBuilds = false`

**Comment by musthafa8230** [comment]
What should I do remove this line or make it true,it's used to reduce the
apk size right

**Comment by Suraj-Tiwari** [comment]
To test just clone this repo then
`cd example/android`
`/gradlew assembleRelease`
Then install production release apk

**Comment by Suraj-Tiwari** [comment]
make it false, app minifiacation is known to causing params issue

**Comment by musthafa8230** [comment]
Sure thanks let me check now

**Comment by musthafa8230** [comment]
Thanks it's working now
